[mgr]
show_hidden = true


[opener]
mpv = [
	{ run = 'mpv "$@"', orphan = true, desc = "Воспроизвести" },
]
eog = [
    { run = 'eog "$@"', orphan = true, desc = "Посмотреть" }
]
code = [
    { run = 'code "$@"', orphan = true, desc = "VSCode" }
]
nvim = [
    { run = 'sudo nvim "$@"', desc = "Neovim", block = true }
]
wallpaper = [
    { run = 'wp set "$0"', desc = "Установить как обои" }
]


[open]
rules = [
	{ mime = "inode/directory", use = [] },
	{ mime = "text/*", use = [ "code", "nvim" ] },
	{ mime = "image/*", use = [ "eog", "wallpaper" ] },
	{ mime = "{audio,video}/*", use = [ "mpv" ] },
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract" ] },
	{ mime = "application/{json,ndjson}", use = [ "code", "nvim" ] },
	{ mime = "*/javascript", use = [ "code", "nvim" ] },
	{ mime = "inode/empty", use = [ "code", "nvim" ] },
	{ mime = "vfs/{absent,stale}", use = "download" },
	#{ url = "*", use = [ "code", "nvim" ] },
]


[plugin]
prepend_preloaders = [
	{ mime = "{audio,video,image}/*", run = "mediainfo" },
	{ mime = "application/subrip", run = "mediainfo" },
	{ mime = "application/postscript", run = "mediainfo" },
]
prepend_previewers = [
	{ mime = "{audio,video,image}/*", run = "mediainfo"},
	{ mime = "application/subrip", run = "mediainfo" },
	{ mime = "application/postscript", run = "mediainfo" },
]



[input]
cursor_blink = false

# cd
cd_title  = " Перейти к: "
cd_origin = "top-center"
cd_offset = [ 0, 2, 50, 3 ]

# create
create_title  = [ " Создать: ", " Создать (дир): " ]
create_origin = "top-center"
create_offset = [ 0, 2, 50, 3 ]

# rename
rename_title  = " Переименовать: "
rename_origin = "hovered"
rename_offset = [ 0, 1, 50, 3 ]

# filter
filter_title  = " Фильтр: "
filter_origin = "top-center"
filter_offset = [ 0, 2, 50, 3 ]

# find
find_title  = [ " Найти дальше: ", " Найти раньше: " ]
find_origin = "top-center"
find_offset = [ 0, 2, 50, 3 ]

# search
search_title  = " Поиск с помощью {n}: "
search_origin = "top-center"
search_offset = [ 0, 2, 50, 3 ]

# shell
shell_title  = [ " Shell: ", " Shell (блок): " ]
shell_origin = "top-center"
shell_offset = [ 0, 2, 50, 3 ]

[confirm]
# trash
trash_title 	= " Удалить выбранные файлы? ({n}) "
trash_origin	= "center"
trash_offset	= [ 0, 0, 70, 20 ]

# delete
delete_title 	= " Удалить безвозвратно выбранные файлы? ({n}) "
delete_origin	= "center"
delete_offset	= [ 0, 0, 70, 20 ]

# overwrite
overwrite_title  = " Перезаписать файл? "
overwrite_body   = "Будет перезаписан следующий файл:"
overwrite_origin = "center"
overwrite_offset = [ 0, 0, 50, 15 ]

# quit
quit_title  = " Выйти? "
quit_body   = "The following tasks are still running, are you sure you want to quit?"
quit_origin = "center"
quit_offset = [ 0, 0, 50, 15 ]

[pick]
open_title  = " Открыть с помощью: "
open_origin = "hovered"
open_offset = [ 0, 1, 50, 7 ]